#!/usr/bin/env bash
# the script that pings an IP address passed as an argument

# ip var
IP="${1}"

# filename var
fn=$(basename "${BASH_SOURCE[@]}")

if ! [ "$IP" ]; then
	echo "Usage: ${fn} {IP_ADDRESS}"
else
	ping -c 5 "${IP}"
fi
